#!/usr/bin/env bash
#Installs Nginx and configure it

#Install nginx
sudo apt-get update
sudo apt-get install -y nginx

#!/bin/bash

# Install Nginx web server
# sudo apt-get update
# sudo apt-get install nginx -y

# Configure Nginx to redirect /redirect_me to another page
sudo sed -i '/^\s*location \/ {$/a \\n    location /redirect_me {\n        return 301 https://www.github.com/;\n    }\n' /etc/nginx/sites-available/default

# Remove duplicate location block
sudo sed -i '/location \/redirect_me {/,/}/d' /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

#Restart Nginx
sudo service nginx restart
