#!/usr/bin/env bash
# A script that configures a Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Create a new configuration file for the 404 page
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm;

    server_name _;

    location /404.html {
        internal;
        root /var/www/html;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
        return 404 "Ceci n'est pas une page.\n";
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Test the configuration file to make sure it's valid
nginx -t

# If the configuration file is valid, reload Nginx to apply the new configuration
if nginx -t; then
    service nginx reload
fi
