#!/usr/bin/env bash

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure Nginx to use the custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-available/default' <<EOF
server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;

   location /redirect_me {
      return 301 https://www.github.com/;
   }

   error_page 404 /404.html;
   location = /404.html {
      root /var/www/html;
      internal;
   }
}
EOF

# Restart Nginx
sudo service nginx restart
