#!/usr/bin/env bash
# A Bash script to make nginx to listen at port 80
#sudo service nginx start
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
#sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restarts
