#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user

# Change Nginx user to nginx
sed -i 's/user\s*\(.*\);/user nginx;/g' /etc/nginx/nginx.conf

# Update Nginx default site configuration to listen on port 8080 and all IPs
sed -i 's/listen\s*\(.*\)/listen 8080;\n\tlisten \1;/g' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
