#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user

# Add nginx user
adduser --disabled-password --gecos "" nginx

# Modify Nginx configuration
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
