#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user
adduser --disabled-password --gecos "" nginx
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default
service nginx restart

