#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user
service nginx stop
sed -i 's/user\s*nginx;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/www/html /var/log/nginx /var/lib/nginx
service nginx start

